disabled_rules:
 - colon
 - comma
 - control_statement
 - trailing_whitespace
 - identifier_name
 - force_try
 - type_name
 - force_cast
 - line_length
 - large_tuple
 - trailing_comma
 - inclusive_language
 - missing_docs

opt_in_rules:
 - empty_count
 - missing_docs

excluded:
 - fastlane
 - Packages
 - Tuist

included:
 - Azkar

file_length:
 warning: 500
 error: 800

type_body_length:
 warning: 300
 error: 500
 
function_body_length:
 warning: 150
 error: 200

reporter: xcode

function_parameter_count:
 warning: 5
 error: 10

warning_threshold: 200

cyclomatic_complexity:
 ignores_case_statements: true

nesting:
 type_level: 3
