disabled_rules:
 - colon
 - comma
 - control_statement
 - trailing_whitespace
 - identifier_name
 - force_try
 - type_name
 - force_cast

opt_in_rules:
 - empty_count
 - missing_docs

excluded:
 - fastlane
 - Packages
 - Tuist

included:
 - Azkar

line_length:
 warning: 300
 error: 500

file_length:
 warning: 200
 error: 500

type_body_length:
 warning: 200
 error: 500
 
function_body_length:
 warning: 50
 error: 200

reporter: xcode

function_parameter_count:
 warning: 5
 error: 10

warning_threshold: 200

cyclomatic_complexity:
 ignores_case_statements: true
