# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do |options|
  	changelog = File.read("./changelog")
  	api_key_path = "fastlane/AuthKey.json"
  	match(api_key_path: api_key_path, type: options[:type] ||= 'appstore', readonly: options[:force_match] == false)
    increment_build_number(xcodeproj: "Azkar.xcodeproj")
    build_app(scheme: "Azkar")
    testflight(api_key_path: api_key_path, changelog: changelog)
  end
end
